/* Vehicle A State Data */
export const vehicleAData = JSON.parse(`{
    "id":[ 12345678901234567, "int"],
    "user_id":[ 123, "int"],
    "vehicle_id":[ 1234567890, "int"],
    "vin":[ "5YJSA11111111111", "string"],
    "display_name":[ "Nikola 2.0", "string"],
    "option_codes":[ "AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0", "string"],
    "color":[ null, "string"],
    "access_type":[ "OWNER", "string"],
    "tokens":["[\\"abcdef1234567890\\", \\"1234567890abcdef\\"]", "json"],
    "state":[ "online", "string"],
    "in_service":[ false, "boolean"],
    "id_s":[ "12345678901234567", "string"],
    "calendar_enabled":[ true, "boolean"],
    "api_version":[ 13, "int"],
    "backseat_token":[ null, "string"],
    "backseat_token_updated_at":[ null, "string"]
}`);

export const vehicleAChargeState = JSON.parse(`{
    "battery_heater_on":[ false, "boolean"],
    "battery_level":[ 59, "int"],
    "battery_range":[ 149.92, "float"],
    "charge_current_request":[ 40, "int"],
    "charge_current_request_max":[ 40, "int"],
    "charge_enable_request":[ true, "boolean"],
    "charge_energy_added":[ 2.42, "float"],
    "charge_limit_soc":[ 90, "int"],
    "charge_limit_soc_max":[ 100, "int"],
    "charge_limit_soc_min":[ 50, "int"],
    "charge_limit_soc_std":[ 90, "int"],
    "charge_miles_added_ideal":[ 10.0, "float"],
    "charge_miles_added_rated":[ 8.0, "float"],
    "charge_port_cold_weather_mode":[ null, "string"],
    "charge_port_door_open":[ true, "boolean"],
    "charge_port_latch":[ "Engaged", "string"],
    "charge_rate":[ 28.0, "float"],
    "charge_to_max_range":[ false, "boolean"],
    "charger_actual_current":[ 40, "int"],
    "charger_phases":[ 1, "int"],
    "charger_pilot_current":[ 40, "int"],
    "charger_power":[ 9, "int"],
    "charger_voltage":[ 243, "int"],
    "charging_state":[ "Charging", "string"],
    "conn_charge_cable":[ "SAE", "string"],
    "est_battery_range":[ 132.98, "float"],
    "fast_charger_brand":[ "<invalid>", "string"],
    "fast_charger_present":[ false, "boolean"],
    "fast_charger_type":[ "<invalid>", "string"],
    "ideal_battery_range":[ 187.4, "float"],
    "managed_charging_active":[ false, "boolean"],
    "managed_charging_start_time":[ null, "string"],
    "managed_charging_user_canceled":[ false, "boolean"],
    "max_range_charge_counter":[ 0, "int"],
    "minutes_to_full_charge":[ 165, "int"],
    "not_enough_power_to_heat":[ false, "boolean"],
    "scheduled_charging_pending":[ false, "boolean"],
    "scheduled_charging_start_time":[ null, "string"],
    "time_to_full_charge":[ 2.75, "float"],
    "timestamp":[ 1607623897515, "int"],
    "trip_charging":[ false, "boolean"],
    "usable_battery_level":[ 59, "int"],
    "user_charge_enable_request":[ null, "string"]
}`);
export const vehicleADriveState = JSON.parse(`{
    "gps_as_of":[ 1543187664,"int"],
    "heading":[ 8,"int"],
    "latitude":[ 33.111111,"float"],
    "longitude":[ -88.111111,"float"],
    "native_latitude":[ 33.111111,"float"],
    "native_location_supported":[ 1,"int"],
    "native_longitude":[ -88.111111,"float"],
    "native_type":[ "wgs","string"],
    "power":[ 0,"int"],
    "shift_state":[ null,"string"],
    "speed":[ null,"int"],
    "timestamp":[ 1543187666472, "int"]
}`);
export const vehicleAClimateState = JSON.parse(`{
    "battery_heater":[ false,"boolean"],
    "battery_heater_no_power":[ false,"boolean"],
    "climate_keeper_mode":[ "off","string"],
    "defrost_mode":[ 0,"int"],
    "driver_temp_setting":[ 21.1,"float"],
    "fan_status":[ 0,"int"],
    "inside_temp":[ 22.1,"float"],
    "is_auto_conditioning_on":[ false,"boolean"],
    "is_climate_on":[ false,"boolean"],
    "is_front_defroster_on":[ false,"boolean"],
    "is_preconditioning":[ false,"boolean"],
    "is_rear_defroster_on":[ false,"boolean"],
    "left_temp_direction":[ -66,"in"],
    "max_avail_temp":[ 28.0,"float"],
    "min_avail_temp":[ 15.0,"float"],
    "outside_temp":[ 18.0,"float"],
    "passenger_temp_setting":[ 21.1,"float"],
    "remote_heater_control_enabled":[ false,"boolean"],
    "right_temp_direction":[ -66,"int"],
    "seat_heater_left":[ 0,"int"],
    "seat_heater_right":[ 0,"int"],
    "side_mirror_heaters":[ false,"boolean"],
    "timestamp":[ 1607623897515,"int"],
    "wiper_blade_heater":[ false,"boolean"]
}`);
export const vehicleAGuiSettings = JSON.parse(`{
    "gui_24_hour_time":[ false,"boolean"],
    "gui_charge_rate_units":[ "mi/hr","string"],
    "gui_distance_units":[ "mi/hr","string"],
    "gui_range_display":[ "Rated","string"],
    "gui_temperature_units":[ "F","string"],
    "show_range_units":[ true,"boolean"],
    "timestamp":[ 1607623897515, "int"]
}`);
export const vehicleAVehicleState = JSON.parse(`{
    "api_version":[ 10,"int"],
    "autopark_state_v2":[ "standby","string"],
    "autopark_style":[ "standard","string"],
    "calendar_supported":[ true,"boolean"],
    "car_version":[ "2020.36.16 3e9e4e8dd287","string"],
    "center_display_state":[ 0,"int"],
    "fd_window": [0,"int"],
    "rd_window": [0,"int"],
    "fp_window": [0,"int"],
    "rp_window": [0,"int"],
    "df":[ 0,"int"],
    "dr":[ 0,"int"],
    "ft":[ 0,"int"],
    "homelink_device_count":[ 2,"int"],
    "homelink_nearby":[ true,"boolean"],
    "is_user_present":[ false,"boolean"],
    "last_autopark_error":[ "no_error","string"],
    "locked":[ false,"boolean"],
    "media_state":[ "{ \\"remote_control_enabled\\": true }","json"],
    "notifications_supported":[ true,"boolean"],
    "odometer":[ 57509.856033,"float"],
    "parsed_calendar_supported":[ true,"boolean"],
    "pf":[ 0,"int"],
    "pr":[ 0,"int"],
    "remote_start":[ false,"boolean"],
    "remote_start_enabled":[ true,"boolean"],
    "remote_start_supported":[ true,"boolean"],
    "rt":[ 0,"int"],
    "sentry_mode":[ false,"boolean"],
    "sentry_mode_available":[ true,"boolean"],
    "smart_summon_available":[ true,"boolean"],
    "software_update": ["{\\"download_perc\\":0,\\"expected_duration_sec\\":2700,\\"install_perc\\":1,\\"status\\":\\"\\",\\"version\\":\\"\\"}","json"],
    "speed_limit_mode": ["{ \\"active\\": false, \\"current_limit_mph\\": 50.0, \\"max_limit_mph\\": 90, \\"min_limit_mph\\": 50, \\"pin_code_set\\": true }", "json"],
    "summon_standby_mode_enabled":[ false,"boolean"],
    "sun_roof_percent_open":[ 0,"int"],
    "sun_roof_state":[ "closed","string"],
    "timestamp":[ 1604977470379,"int"],
    "tpms_pressure_fl":[ null,"string"],
    "tpms_pressure_fr":[ null,"string"],
    "tpms_pressure_rl":[ null,"string"],
    "tpms_pressure_rr":[ null,"string"],
    "valet_mode":[ false,"boolean"],
    "valet_pin_needed":[ true,"boolean"],
    "vehicle_name":[ "Nikola 2.0", "string"]
}`);
export const vehicleAVehicleConfig = JSON.parse(`{
    "can_accept_navigation_requests":[ true,"boolean"],
    "can_actuate_trunks":[ true,"boolean"],
    "car_special_type":[ "base","string"],
    "car_type":[ "models2","string"],
    "charge_port_type":[ "US","string"],
    "ece_restrictions":[ false,"boolean"],
    "eu_vehicle":[ false,"boolean"],
    "exterior_color":[ "White","string"],
    "has_air_suspension":[ true,"boolean"],
    "has_ludicrous_mode":[ false,"boolean"],
    "motorized_charge_port":[ true,"boolean"],
    "plg":[ true,"boolean"],
    "rear_seat_heaters":[ 0,"int"],
    "rear_seat_type":[ 0,"int"],
    "rhd":[ false,"boolean"],
    "roof_color":[ "None","string"],
    "seat_type":[ 2,"int"],
    "spoiler_type":[ "None","string"],
    "sun_roof_installed":[ 2,"int"],
    "third_row_seats":[ "None","string"],
    "timestamp":[ 1604977445448,"int"],
    "trim_badging":[ "p90d","string"],
    "use_range_badging":[ false,"boolean"],
    "wheel_type":[ "AeroTurbine19","string"]
}`);
export const vehicleAMobileEnabled = { response: [true, "boolean"] };
